import smtplib, ssl
import logging
import logging.handlers

logging.basicConfig(filename="crawler.log",
                            filemode='a',
                            format='%(asctime)s,%(msecs)d %(name)s %(levelname)s %(message)s',
                            datefmt='%H:%M:%S',
                            level=logging.DEBUG)

logger = logging.getLogger('email_bot')

def send_email(title, details):
        
    port = 465  # For SSL
    smtp_server = "smtp.gmail.com"
    sender_email = ""  # Enter your address
    receiver_emails = [""]
    password = ""

    message = """From: %s\nTo: %s\nSubject: %s\n\n%s\n%s
    """ % (sender_email, ", ".join(receiver_emails), f"Free Food: {title}", details, "This message is generated by anhTimeLimitExceeded's bot")
    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_emails, message)
        logger.info(f"emails-sent to: {receiver_emails}")
